name: Plugin CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: test
        run:  mvn -ntp clean test
        
      - name: maven-settings-action
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: |
            [{
                "id": "azalea-repo",
                "username": "${{ secrets.REPO_USERNAME }}",
                "password": "${{ secrets.REPO_PASSWORD }}"
            }]

      - name: deploy
        run:  mvn deploy
